version: "3"
services:

  nginx:
    image: nginx:1.23.3-alpine
    container_name: 'minifram-nginx'
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./minifram-php:/var/www/minifram-php
    links:
      - php
    networks:
      - bridge

  php:
    build: docker/php
    volumes:
      - ./minifram-php:/var/www/minifram-php
    networks:
      - bridge

  mysql:
    image: mysql:8.0.32
    container_name: 'minifram-mysql'
    volumes:
      - ./docker/mysql:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: minifram
      MYSQL_USER: user
      MYSQL_PASSWORD: userpasswd
      MYSQL_RANDOM_ROOT_PASSWORD: true
    restart: always
    networks:
      - bridge

networks:
  bridge:
    driver: bridge